FROM --platform=$BUILDPLATFORM golang:1.26-bookworm AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY internal ./internal
COPY hack/trustedproxy ./hack/trustedproxy
ARG TARGETOS=linux
ARG TARGETARCH=arm64
RUN CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH go build -trimpath -ldflags='-s -w' -o /out/trustedproxy ./hack/trustedproxy

FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=build /out/trustedproxy /usr/local/bin/trustedproxy
USER 65532:65532
ENTRYPOINT ["/usr/local/bin/trustedproxy"]
