// Copyright (c) 2026 Idriss ELIGUENE
// Author: Idriss ELIGUENE <idriss.eliguene@gmail.com>
// SPDX-License-Identifier: Apache-2.0 OR MIT
//
// Part of the landlock-genprof project.

//go:build gendocs

// Command gendocs (built via `-tags gendocs`, mutually exclusive with the
// real landlock-genprof main() in main.go — exactly one of the two is
// ever compiled in) regenerates the CLI reference under book/src/cli/
// from the actual cobra command tree (newRootCmd, same one the real
// binary runs), via cobra's own doc.GenMarkdownTree. Kept out of the
// shipped binary entirely — spf13/cobra/doc has no reason to be a
// runtime dependency of the actual tool — rather than a hidden
// subcommand on the real root command.
//
// Usage: go run -tags gendocs ./cmd/landlock-genprof <output-dir>
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra/doc"
)

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintln(os.Stderr, "usage: go run -tags gendocs ./cmd/landlock-genprof <output-dir>")
		os.Exit(1)
	}
	outDir := os.Args[1]

	if err := os.MkdirAll(outDir, 0o755); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	root := newRootCmd()
	root.DisableAutoGenTag = true // no "Auto generated by spf13/cobra on <date>" footer — regenerated on every docs build, a timestamp would just be diff noise
	if err := doc.GenMarkdownTree(root, outDir); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	if err := normalizeGeneratedCLI(outDir); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

// normalizeGeneratedCLI annotates the plain-text Markdown emitted by Cobra.
// mdBook treats an unannotated fenced block as a Rust doctest. CLI synopsis
// and option listings are documentation text, while Examples are shell
// invocations; neither should be compiled as Rust.
func normalizeGeneratedCLI(root string) error {
	return filepath.WalkDir(root, func(path string, entry os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() || filepath.Ext(path) != ".md" {
			return nil
		}

		content, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		normalized := normalizeGeneratedCLIPage(string(content))
		if normalized == string(content) {
			return nil
		}
		return os.WriteFile(path, []byte(normalized), 0o644)
	})
}

func normalizeGeneratedCLIPage(content string) string {
	lines := strings.SplitAfter(content, "\n")
	section := ""
	inFence := false
	for i, line := range lines {
		trimmed := strings.TrimSuffix(strings.TrimSuffix(line, "\n"), "\r")
		switch {
		case strings.HasPrefix(trimmed, "### "):
			section = strings.TrimSpace(strings.TrimPrefix(trimmed, "### "))
		case strings.HasPrefix(trimmed, "```"):
			if inFence {
				inFence = false
				continue
			}
			inFence = true
			if trimmed != "```" {
				continue
			}
			language := "text"
			if section == "Examples" {
				language = "sh"
			}
			lines[i] = strings.Replace(line, "```", "```"+language, 1)
		}
	}
	return strings.Join(lines, "")
}
