// Copyright (c) 2026 Idriss ELIGUENE
// Author: Idriss ELIGUENE <idriss.eliguene@gmail.com>
// SPDX-License-Identifier: Apache-2.0 OR MIT
//
// Part of the landlock-genprof project.

//go:build gendocs

// Command gendocs (built via `-tags gendocs`, mutually exclusive with the
// real landlock-genprof main() in main.go — exactly one of the two is
// ever compiled in) regenerates the CLI reference under book/src/cli/
// from the actual cobra command tree (newRootCmd, same one the real
// binary runs), via cobra's own doc.GenMarkdownTree. Kept out of the
// shipped binary entirely — spf13/cobra/doc has no reason to be a
// runtime dependency of the actual tool — rather than a hidden
// subcommand on the real root command.
//
// Usage: go run -tags gendocs ./cmd/landlock-genprof <output-dir>
package main

import (
	"fmt"
	"os"

	"github.com/spf13/cobra/doc"
)

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintln(os.Stderr, "usage: go run -tags gendocs ./cmd/landlock-genprof <output-dir>")
		os.Exit(1)
	}
	outDir := os.Args[1]

	if err := os.MkdirAll(outDir, 0o755); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	root := newRootCmd()
	root.DisableAutoGenTag = true // no "Auto generated by spf13/cobra on <date>" footer — regenerated on every docs build, a timestamp would just be diff noise
	if err := doc.GenMarkdownTree(root, outDir); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
