package main

import "net/http"

func handleWorkbenchScript(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet || r.URL.Path != "/workbench.js" {
		w.Header().Set("Allow", http.MethodGet)
		http.Error(w, "read-only Workbench: GET only", http.StatusMethodNotAllowed)
		return
	}
	w.Header().Set("Content-Type", "text/javascript; charset=utf-8")
	_, _ = w.Write([]byte(workbenchScript))
}

const workbenchScript = `(function () {
  "use strict";
  const app = document.getElementById("observation-workbench");
  if (!app) return;
  const picker = app.querySelector("#workload-picker"), detail = app.querySelector("#observation-detail"), message = app.querySelector("#workbench-message");
  const value = (o, lower, upper) => o && (o[lower] !== undefined ? o[lower] : o[upper]);
  const state = (v) => v == null || v === "" ? "NOT_AVAILABLE" : String(v);
  const clear = (node) => { while (node && node.firstChild) node.removeChild(node.firstChild); };
  const text = (tag, content, className) => { const node = document.createElement(tag); node.textContent = String(content == null ? "" : content); if (className) node.className = className; return node; };
  const stateCopy = (raw) => ({POPULATION_PRESENT:"Accumulated population record available",POPULATION_NOT_FOUND:"No accumulated population record",AVAILABLE:"Evidence available",EMPTY:"No attributed evidence observed",UNKNOWN:"Evidence state unknown",NONE:"No current valid approved policy",SELECTED:"Valid approved policy",APPROVED:"Valid approved policy",AMBIGUOUS:"Multiple valid approved policies",STALE_APPROVAL:"Approval no longer validates current candidate context",NOT_ATTEMPTED:"No recorded application attempt",APPLIED:"Latest recorded application outcome: applied",PARTIALLY_APPLIED:"Latest recorded application outcome: partially applied",FAILED:"Latest recorded application outcome: failed",OUTCOME_UNKNOWN:"Latest application outcome: unknown",ROLLED_BACK:"Latest recorded state: rolled back",ROLLBACK_FAILED:"Latest rollback outcome: failed",ROLLBACK_OUTCOME_UNKNOWN:"Latest rollback outcome: unknown",IN_PROGRESS:"Latest application attempt is in progress",ROLLBACK_IN_PROGRESS:"Latest rollback attempt is in progress",NOT_PROJECTABLE_AMBIGUOUS_GOVERNANCE:"Application projection unavailable because multiple valid approved Proposals exist",CONFIRMED_AT_APPLICATION:"Kubernetes object matched the intended spec immediately after application",PARTIAL:"Some mutation records have structural confirmation",NOT_CONFIRMED:"No structural confirmation recorded"}[raw] || raw);
  const axisCopy = (label, raw) => { if (label === "Application" && raw === "UNKNOWN") return "Latest application outcome: unknown"; if (label === "Structural knowledge" && raw === "NONE") return "No structural confirmation recorded"; if (label === "Behavioral verification") return "Behavioral verification: unknown"; return stateCopy(raw); };
  function showError(e) { message.textContent = e && e.reason ? e.reason : "Unable to load governance data; authoritative state was not changed."; }
  async function get(url, options) { const response = await fetch(url, Object.assign({headers:{"Accept":"application/json"}}, options || {})); const body = await response.json().catch(() => ({})); if (!response.ok) throw body; return body; }
  function subjectQuery(subject) { const q = new URLSearchParams(); q.set("scope", value(subject,"scope","Scope") || ""); q.set("target", value(subject,"target","Target") || ""); q.set("container", value(subject,"container","Container") || ""); q.set("imageIdentity", value(subject,"imageIdentity","ImageIdentity") || ""); q.set("binaryPath", value(subject,"binaryPath","BinaryPath") || ""); return q.toString(); }
  function appendState(parent, label, raw) { const card = document.createElement("div"); card.className = "g8-state card"; card.appendChild(text("strong", label)); card.appendChild(text("span", state(raw), "state")); parent.appendChild(card); }
  function attentionCopy(code) { const copies = {CAPABILITY_OUTSIDE_APPROVED_POLICY:"Observed capability outside approved policy", APPROVED_NOT_APPLIED:"Approved policy lacks a successful latest application record", APPLICATION_STATE_UNKNOWN:"Latest application outcome is unknown", NEW_CONTRIBUTION_SINCE_CANDIDATE:"New Observation contribution since latest candidate", OBSERVATION_FAILED_BOUND:"Observation failed for this population", OBSERVATION_FAILED_UNBOUND:"Observation failed before exact population attribution", MULTIPLE_VALID_APPROVED_PROPOSALS:"Multiple valid approved Proposals"}; return copies[code] || code || "Attention reason"; }
  function renderEnvironment(body) {
    const list = app.querySelector("#environment-list"), attention = app.querySelector("#attention-list"), overview = app.querySelector("#overview-summary"); clear(list); clear(attention); clear(overview);
    const entries = body.items || [], truncated = Boolean(body.truncated);
    overview.appendChild(text("p", truncated ? "Showing a bounded subset of the available Environment subjects." : "Environment subjects represented by the current durable data: " + entries.length)); overview.appendChild(text("p", "Unattributed failed Observations: " + (body.unattributedFailedObservationCount || 0)));
    if (!entries.length) list.appendChild(text("p", "No Environment subjects are represented by the current durable data."));
    entries.forEach((entry) => {
      const subject = value(entry,"subject","Subject") || {}, card = document.createElement("article"); card.className = "card environment-entry";
      const title = document.createElement("h3"); title.appendChild(text("span", value(subject,"scope","Scope") + " · " + value(subject,"target","Target") + " · " + value(subject,"container","Container"))); card.appendChild(title);
      card.appendChild(text("p", "Image: " + value(subject,"imageIdentity","ImageIdentity") + (value(subject,"binaryPath","BinaryPath") ? " · Binary: " + value(subject,"binaryPath","BinaryPath") : "")));
      const states = document.createElement("div"); states.className = "state-grid"; appendState(states,"Population",axisCopy("Population",value(entry,"populationPresence","PopulationPresence"))); appendState(states,"Governance",axisCopy("Governance",value(entry,"governance","Governance"))); appendState(states,"Application",axisCopy("Application",value(entry,"application","Application"))); appendState(states,"Structural knowledge",axisCopy("Structural knowledge",value(entry,"structural","Structural"))); appendState(states,"Behavioral verification",axisCopy("Behavioral verification","UNKNOWN")); card.appendChild(states);
      const evidence = value(entry,"observationEvidence","ObservationEvidence") || []; const evidenceList = document.createElement("ul"); evidenceList.appendChild(text("li", "Evidence summaries")); evidence.forEach((item) => evidenceList.appendChild(text("li", item.source + ": " + (item.evidenceState === "UNKNOWN" ? "Evidence state unknown" : stateCopy(item.evidenceState))))); card.appendChild(evidenceList);
      if (value(entry,"proposalSubjectMatchedMultipleWorkloadUIDs","ProposalSubjectMatchedMultipleWorkloadUIDs") === true) card.appendChild(text("p","Multiple workload UIDs were observed for this Proposal-compatible subject.","boundary"));
      const reasons = value(entry,"attention","Attention") || []; if (reasons.length) card.appendChild(text("p","Attention: " + reasons.map((r) => value(r,"category","Category")).join(", "),"notice"));
      const history = document.createElement("button"); history.type = "button"; history.textContent = "Open subject history"; history.addEventListener("click", () => loadHistory(subject)); card.appendChild(history); list.appendChild(card);
      reasons.forEach((reason) => { const item = document.createElement("li"); item.appendChild(text("strong", value(reason,"category","Category") + ": ")); item.appendChild(text("span", attentionCopy(value(reason,"explanationCode","ExplanationCode")))); attention.appendChild(item); });
    });
    if (!attention.children.length) attention.appendChild(text("p", "No Attention reasons in the current bounded projection.")); app.querySelector("#environment-boundary").textContent = body.limitation || "BEST_EFFORT_MULTI_OBJECT_READ";
  }
  async function loadEnvironment() { try { renderEnvironment(await get("/api/v08/environment")); message.textContent = ""; } catch (e) { showError(e); } }
  function renderHistory(body) { const history = body.history || {}, panel = app.querySelector("#history-detail"); clear(panel); panel.appendChild(text("h3","History drill-down")); panel.appendChild(text("p",body.limitation || "BEST_EFFORT_MULTI_OBJECT_READ","boundary")); const events = history.timestampedEvents || history.TimestampedEvents || [], facts = history.untimestampedFacts || history.UntimestampedFacts || [], limitations = history.limitations || history.Limitations || []; panel.appendChild(text("h4","Timestamped events")); if (!events.length) panel.appendChild(text("p","No timestamped events are durably recorded.")); events.forEach((event) => panel.appendChild(text("p",(value(event,"kind","Kind") || "EVENT") + " · " + (value(event,"timestamp","Timestamp") || "timestamp unavailable") + " · " + (value(event,"detailCode","DetailCode") || "")))); panel.appendChild(text("h4","Untimestamped / unordered facts")); if (!facts.length) panel.appendChild(text("p","No untimestamped facts are durably recorded.")); facts.forEach((fact) => panel.appendChild(text("p",(value(fact,"kind","Kind") || "FACT") + " · " + (value(fact,"detailCode","DetailCode") || "")))); if (limitations.length) panel.appendChild(text("p","Limitations: " + limitations.join(", "),"notice")); }
  async function loadHistory(subject) { try { renderHistory(await get("/api/v08/history?" + subjectQuery(subject))); showView("history"); } catch (e) { showError(e); } }
  function renderObservation(o) { clear(detail); const h = document.createElement("h3"); h.appendChild(text("span","Observation ")); h.appendChild(text("code",o.observationID)); detail.appendChild(h); detail.appendChild(text("p","Execution: " + state(o.execution && o.execution.state) + " · Frozen: " + String(o.frozen))); const sources = document.createElement("ul"); (o.sources || []).forEach((source) => sources.appendChild(text("li",source.name + " · attribution " + state(source.attributionState) + " · evidence " + state(source.evidenceState)))); detail.appendChild(sources); }
  async function load(c) { const q = new URLSearchParams({kind:c.kind,name:c.name,container:c.container,workloadUID:c.uid,group:c.group || "",imageIdentity:c.image || ""}); try { const observations = await get("/api/observations?" + q), list = app.querySelector("#observation-list"); clear(list); (observations.items || []).forEach((item) => { const li = document.createElement("li"), button = document.createElement("button"); button.type = "button"; button.textContent = item.observationID; button.addEventListener("click", async () => { selectedObservation = await get("/api/observations/" + encodeURIComponent(item.observationID)); renderObservation(selectedObservation); }); li.appendChild(button); li.appendChild(text("span"," · " + state(item.execution && item.execution.state))); list.appendChild(li); }); if (!list.children.length) list.appendChild(text("li","No durable Observations for this identity.")); const proposals = await get("/api/proposals?" + q), proposalList = app.querySelector("#proposal-list"); clear(proposalList); (proposals.items || []).forEach((item) => proposalList.appendChild(text("li",item.name + " · " + state(item.status && item.status.approvalState)))); if (!proposalList.children.length) proposalList.appendChild(text("li","No durable Proposals for this subject.")); } catch (e) { showError(e); } }
  async function workloads() { try { picker.length = 1; const data = await get("/api/workloads"); (data.workloads || []).forEach((workload) => (workload.pods || []).forEach((pod) => (pod.containers || []).forEach((container) => { if (!container.target) return; const option = document.createElement("option"); option.textContent = workload.target.kind + "/" + workload.target.name + " · " + container.name + " · pod " + pod.uid; option.dataset.context = JSON.stringify({pod:pod.name,group:workload.target.group,kind:workload.target.kind,name:workload.target.name,container:container.name,uid:workload.uid || pod.uid,image:container.runtime && container.runtime.imageID || ""}); picker.appendChild(option); })))); } catch (e) { showError(e); } }
  function showView(name) { ["overview","environment","attention","observations","proposals","history"].forEach((view) => { const node = app.querySelector("#" + view + "-view"); if (node) node.hidden = view !== name; }); }
  let selectedContext = null, selectedObservation = null;
  app.querySelectorAll("[data-view]").forEach((button) => button.addEventListener("click", () => { showView(button.dataset.view); if (["overview","environment","attention"].includes(button.dataset.view)) loadEnvironment(); }));
  picker.onchange = () => { if (picker.selectedIndex) { selectedContext = JSON.parse(picker.options[picker.selectedIndex].dataset.context); load(selectedContext); } };
  document.querySelector("#start-observation").onclick = async () => { if (!selectedContext) return showError({reason:"Select a workload/container first."}); try { await post("/api/observations/start", {namespace:app.dataset.namespace,pod:selectedContext.pod,container:selectedContext.container,sources:["filesystem"],duration:60000000000}); await load(selectedContext); } catch (e) { showError(e); } };
  document.querySelector("#stop-observation").onclick = async () => { if (!selectedObservation) return showError({reason:"Select an Observation first."}); try { await post("/api/observations/stop", {namespace:app.dataset.namespace,observationID:selectedObservation.observationID}); await load(selectedContext); } catch (e) { showError(e); } };
  document.querySelector("#generate-proposal").onclick = async () => { if (!selectedObservation) return showError({reason:"Select a completed Observation first."}); try { await post("/api/observations/generate-proposal", {namespace:app.dataset.namespace,observationID:selectedObservation.observationID,proposalName:"observation-" + selectedObservation.observationID}); await load(selectedContext); } catch (e) { showError(e); } };
  async function post(url, body) { return get(url, {method:"POST",headers:{"Accept":"application/json","Content-Type":"application/json"},body:JSON.stringify(body)}); }
  app.querySelector("#refresh-workbench").onclick = () => { workloads(); loadEnvironment(); }; showView("overview"); workloads(); loadEnvironment();
})();`
